platform :ios, '6.0'
pod 'ASIHTTPRequest', '~>1.8.1'
pod 'NSData+Base64', '~> 1.0.0'
pod 'CollapseClick', '~> 1.0.1'
pod 'UI7Kit'
pod 'AZTools', :podspec => 'https://raw.github.com/gbammc/AZTools/master/AZTools.podspec'
pod 'FPBrandColors',  '~> 0.1.3'
pod 'MBProgressHUD', '~> 0.8'